;;; literate-config-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from literate-config.el

(autoload 'literate-config-compile "literate-config" "\
Write all source blocks from =config.org= into =config.el= that:
- Are not marked as `tangle: no'
- Don't have the TODO state `DISABLED'
- Have a source-code of `emacs-lisp'")
(autoload 'literate-config-ensure-compiled "literate-config" "\
Compile the config if it does not exist or the source config has changed.")
(autoload 'literate-config-load "literate-config" "\
Load the config.")
(autoload 'literate-config-init "literate-config" "\
Compile, install hooks, and load the config.")
(register-definition-prefixes "literate-config" '("literate-config-"))

;;; End of scraped data

(provide 'literate-config-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; literate-config-autoloads.el ends here
